2019-09-01 17:32:06,816 ERROR: Exception on /reset_password_request [POST] [in c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\tomas\Desktop\Python\Website-with-Flask\microblog\app\routes.py", line 165, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\tomas\Desktop\Python\Website-with-Flask\microblog\app\email.py", line 17, in send_password_reset_email
    token = user.get_reset_password_token()
  File "C:\Users\tomas\Desktop\Python\Website-with-Flask\microblog\app\models.py", line 63, in get_reset_password_token
    return jwt.encode(
AttributeError: module 'jwt' has no attribute 'encode'
2019-09-01 17:34:09,914 INFO: Microblog startup [in C:\Users\tomas\Desktop\Python\Website-with-Flask\microblog\app\__init__.py:44]
2019-09-01 17:34:22,945 ERROR: Exception on /reset_password_request [POST] [in c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\tomas\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\tomas\Desktop\Python\Website-with-Flask\microblog\app\routes.py", line 165, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\tomas\Desktop\Python\Website-with-Flask\microblog\app\email.py", line 17, in send_password_reset_email
    token = user.get_reset_password_token()
  File "C:\Users\tomas\Desktop\Python\Website-with-Flask\microblog\app\models.py", line 64, in get_reset_password_token
    {"reset_password": self.id, "exp": time() + expires_in},
NameError: name 'self' is not defined
2019-09-01 17:36:17,523 INFO: Microblog startup [in C:\Users\tomas\Desktop\Python\Website-with-Flask\microblog\app\__init__.py:44]
